---
# Replace the x's with the IP addresses from "terrafrom output"
dc:
  hosts:
    13.77.149.92:

wef:
  hosts:
    13.66.251.74:

win10:
  hosts:
    13.66.225.219:

exchange:
  hosts:
    52.183.7.185:

